In [ ]:
from google.colab import files

uploaded = files.upload()

Saving drug_side_effects_100k_dataset.csv to drug_side_effects_100k_dataset.csv

In [ ]:
# 1. Count missing values from the raw data
raw_df = pd.read_csv("drug_side_effects_100k_dataset.csv")
before = raw_df[["chronic_condition", "alcohol_use", "recovery_days"]].isnull().sum()

# 2. Count missing values after your cleaning code
after = df[["chronic_condition", "alcohol_use", "recovery_days"]].isnull().sum()

# 3. Combine into a neat summary DataFrame for your report
summary_df = pd.DataFrame({'Missing Before': before, 'Missing After': after})
summary_df

                   Missing Before  Missing After
chronic_condition           16743              0
alcohol_use                 33365              0
recovery_days               11738              0

In [ ]:
# Export the cleaned DataFrame to a new CSV file
df.to_csv("drug_side_effects_100k_cleaned.csv", index=False)

In [ ]:
# 1. Count missing values for ALL columns in the raw data
raw_df = pd.read_csv("drug_side_effects_100k_dataset.csv")
before = raw_df.isnull().sum()

# 2. Count missing values for ALL columns after your cleaning code
after = df.isnull().sum()

# 3. Combine into a complete vertical DataFrame for the report
full_summary_df = pd.DataFrame({'Missing Before': before, 'Missing After': after})
full_summary_df

                      Missing Before  Missing After
patient_id                         0              0
age                                0              0
gender                             0              0
country                            0              0
drug_name                          0              0
dosage_mg                          0              0
side_effect                        0              0
severity                           0              0
outcome                            0              0
report_date                        0              0
treatment_start_date               0              0
chronic_condition              16743              0
smoker                             0              0
alcohol_use                    33365              0
hospitalized                       0              0
recovery_days                  11738              0

In [ ]:
from google.colab import files
files.download("drug_side_effects_100k_cleaned.csv")